# Generated by Django 4.2.6 on 2024-07-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('tech', models.CharField(max_length=255)),
                ('total_minimum_credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GraduationRequirementsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_name', models.CharField(max_length=255)),
                ('minimum_credit', models.IntegerField()),
                ('gr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduation_check.graduationrequirements')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LectureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_group_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('grd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduation_check.graduationrequirementsdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_lecture_group', to='graduation_check.lecturegroup')),
                ('prerequest_lecture_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequest_lecture_group', to='graduation_check.lecturegroup')),
            ],
        ),
        migrations.CreateModel(
            name='LectureLectureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_check.lecture')),
                ('lecture_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_check.lecturegroup')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_groups',
            field=models.ManyToManyField(through='graduation_check.LectureLectureGroup', to='graduation_check.lecturegroup'),
        ),
        migrations.CreateModel(
            name='CommonLectureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_group_name', models.CharField(max_length=255)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_check.lecture')),
            ],
        ),
    ]
