# Generated by Django 4.2.6 on 2024-07-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0002_lecture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonlecturegroup',
            name='lecture',
        ),
        migrations.CreateModel(
            name='CommonLectureGroupLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_lecture_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_check.commonlecturegroup')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_check.lecture')),
            ],
        ),
    ]
