# Generated by Django 4.2.6 on 2024-07-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0003_remove_commonlecturegroup_lecture_and_more'),
    ]

    operations = [
        # 모델 이름 변경
        migrations.RenameModel(
            old_name='GraduationRequirements',
            new_name='Condition',
        ),
        migrations.RenameModel(
            old_name='GraduationRequirementsDetail',
            new_name='LectureCondition',
        ),
        migrations.RenameModel(
            old_name='Lecture',
            new_name='LectureIdentification',
        ),
        migrations.RenameModel(
            old_name='LectureLectureGroup',
            new_name='LectureIdentificationLectureGroup',
        ),
        migrations.RenameModel(
            old_name='CommonLectureGroupLecture',
            new_name='CommonLectureGroupLectureIdentification',
        ),

        # 테이블 이름 변경
        migrations.AlterModelTable(
            name='condition',
            table='graduation_check_graduationrequirements',
        ),
        migrations.AlterModelTable(
            name='lecturecondition',
            table='graduation_check_graduationrequirementsdetail',
        ),
        migrations.AlterModelTable(
            name='lectureidentification',
            table='graduation_check_lecture',
        ),
        migrations.AlterModelTable(
            name='lectureidentificationlecturegroup',
            table='graduation_check_lecturelecturegroup',
        ),
        migrations.AlterModelTable(
            name='commonlecturegrouplectureidentification',
            table='graduation_check_commonlecturegrouplecture',
        ),

        # 필드 이름 변경
        migrations.RenameField(
            model_name='lecturecondition',
            old_name='gr',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='lecturecondition',
            old_name='requirements_name',
            new_name='condition_name',
        ),
        migrations.RenameField(
            model_name='lecturegroup',
            old_name='grd',
            new_name='lecture_condition',
        ),
        migrations.RenameField(
            model_name='lecturegroup',
            old_name='is_mandatory',
            new_name='is_essential',
        ),
        migrations.RenameField(
            model_name='lectureidentificationlecturegroup',
            old_name='lecture',
            new_name='lecture_identification',
        ),
    ]
