# Generated by Django 4.2.6 on 2024-07-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0004_lecturecondition_lectureidentification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonlecturegrouplectureidentification',
            old_name='lecture',
            new_name='lecture_identification',
        ),
        migrations.AlterModelTable(
            name='commonlecturegrouplectureidentification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='condition',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lecturecondition',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lectureidentification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lectureidentificationlecturegroup',
            table=None,
        ),
    ]
