# Generated by Django 4.2.6 on 2024-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0005_rename_lecture_commonlecturegrouplectureidentification_lecture_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
