# Generated by Django 4.2.6 on 2024-09-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0006_prerequest_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLectureGroup',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='graduation_check.lecturegroup')),
                ('minimum_number', models.IntegerField()),
                ('maximum_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lecturegroup',
            name='multi_lecture_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graduation_check.multilecturegroup'),
        ),
    ]
