# Generated by Django 4.2.6 on 2024-09-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0006_prerequest_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLectureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_credit', models.IntegerField()),
                ('maximum_credit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lecturegroup',
            name='multi_lecture_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduation_check.multilecturegroup'),
        ),
    ]
