# Generated by Django 4.2.6 on 2024-09-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_check', '0007_multilecturegroup_lecturegroup_multi_lecture_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multilecturegroup',
            old_name='maximum_credit',
            new_name='maximum_number',
        ),
        migrations.RenameField(
            model_name='multilecturegroup',
            old_name='minimum_credit',
            new_name='minimum_number',
        ),
    ]
